name: dev

on:
  push:
    branches:
      - onekey
      - main
  pull_request:
    branches:
      - onekey
      - main
jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      ENDPOINT: chainlist.test.onekey.so
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@onekeyhq'
          node-version: '16.x'
      - name: Install Dependency
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
      - name: Build Target
        run: |
          yarn build && yarn export
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: ${{ env.ENDPOINT }}
          force_orphan: true
      - name: Comment on PR
        if: ${{ github.ref != 'refs/heads/onekey' }}
        uses: actions/github-script@v3
        env:
          SHA: ${{ github.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `👋 Successfully deployed the latest commit \`${process.env.SHA}\` to https://${process.env.ENDPOINT}`
            })
